```{r}

library(readr)
library(tidyverse)
library(stringr)

# notes: https://ohdsi.github.io/CommonDataModel/cdm60.html#VOCABULARY

#Read in data as separate data frames

concept <- read_tsv(file="V:/FACULTY/DJLEMAS/BENCHMARK_DATA/OMOP2OBO/cancer/data_release/concept_v2.0.txt", show_col_types = FALSE) 

# concept <- read_csv(file="V:/FACULTY/DJLEMAS/BENCHMARK_DATA/OMOP2OBO/cancer/data_release/concept_test.csv", show_col_types = FALSE) 

vocabulary <- read_tsv(file="V:/FACULTY/DJLEMAS/BENCHMARK_DATA/OMOP2OBO/cancer/data_release/vocabulary_v2.0.txt", show_col_types = FALSE) 
concept_ancestor <- read_tsv(file="V:/FACULTY/DJLEMAS/BENCHMARK_DATA/OMOP2OBO/cancer/data_release/concept_ancestor_v2.0.txt", show_col_types = FALSE) %>% rename(concept_id=ancestor_concept_id)
  
#concept_synonym <- read_tsv(file="V:/FACULTY/DJLEMAS/BENCHMARK_DATA/OMOP2OBO/cancer/data_release/concept_synonym_v2.0.txt", show_col_types = FALSE) 
                           

```

```{r}

# created params.R script that contains code below. Run as source from R CLI. 

source("/blue/djlemas/share/data/Benchmark/OMOP/data_release/ufrc/utils/params.R")

# library(readr)
# library(tidyverse)
# library(stringr)
# 
# # data location: /blue/djlemas/share/data/Benchmark/OMOP/data_release/
# 
# # notes: https://ohdsi.github.io/CommonDataModel/cdm60.html#VOCABULARY
# 
# #Read in data as separate data frames
# 
# concept <- read_tsv(file="/blue/djlemas/share/data/Benchmark/OMOP/data_release/concept_v2.0.txt", show_col_types = FALSE)
# 
# # concept <- read_csv(file="/blue/djlemas/share/data/Benchmark/OMOP/data_release/concept_test.csv", show_col_types = FALSE)
# 
# vocabulary <- read_tsv(file="/blue/djlemas/share/data/Benchmark/OMOP/data_release/vocabulary_v2.0.txt", show_col_types = FALSE)
# concept_ancestor <- read_tsv(file="/blue/djlemas/share/data/Benchmark/OMOP/data_release/concept_ancestor_v2.0.txt", show_col_types = FALSE) %>% rename(concept_id=ancestor_concept_id)
# 
# concept_synonym <- read_tsv(file="/blue/djlemas/share/data/Benchmark/OMOP/data_release/concept_synonym_v2.0.txt", show_col_types = FALSE)
                           

```



```{r}

# Create Condition Concepts Dataset (condition_concept_df)

# Merge the Concept table with the Vocabulary table:  Primary key: concept_id 
                             
condition_concept_df_tmp=full_join(concept,vocabulary,by='vocabulary_id') %>% 
  filter(concept_name != "No matching concept",
         domain_id == "Condition",
         standard_concept == "S",
         vocabulary_id == "SNOMED") 

# create CONCEPT_SOURCE_CODE
CONCEPT_SOURCE_CODE_tmp=condition_concept_df_tmp %>%
  group_by(concept_id) %>%
  mutate(tmp_vocab_id = paste0(tolower(vocabulary_id),":",tolower(concept_code))) %>%
  distinct(tmp_vocab_id,.keep_all = TRUE) %>%
  # mutate(test=n_distinct(tmp_vocab_id)) %>%
  summarize(CONCEPT_SOURCE_CODE = str_c(tmp_vocab_id, collapse = "| ")) 
  
    # check
    # head(CONCEPT_SOURCE_CODE_tmp)
    # table(CONCEPT_SOURCE_CODE_tmp$test)
    # dim(CONCEPT_SOURCE_CODE_tmp)
    # dim(condition_concept_df_tmp)

# create CONCEPT_SOURCE_LABEL
CONCEPT_SOURCE_LABEL_tmp=condition_concept_df_tmp %>%
  group_by(concept_id) %>%
  distinct(concept_name,.keep_all = TRUE) %>%
  # mutate(test=n_distinct(concept_name)) %>%
  summarize(CONCEPT_SOURCE_LABEL = str_c(concept_name, collapse = "| "))

    # check
    # head(CONCEPT_SOURCE_LABEL_tmp)
    # table(CONCEPT_SOURCE_LABEL_tmp$test)
    # dim(CONCEPT_SOURCE_LABEL_tmp)
    # dim(condition_concept_df_tmp)

# create CONCEPT_VOCAB
CONCEPT_VOCAB_tmp=condition_concept_df_tmp %>%
  group_by(concept_id) %>%
  distinct(vocabulary_id,.keep_all = TRUE) %>%
  # mutate(test=n_distinct(vocabulary_id)) %>%
  summarize(CONCEPT_VOCAB = str_c(tolower(vocabulary_id), collapse = "| "))
         
    # check
    # head(CONCEPT_VOCAB_tmp)
    # table(CONCEPT_VOCAB_tmp$test)
    # dim(CONCEPT_VOCAB_tmp)
    # dim(condition_concept_df_tmp)

# create CONCEPT_VOCAB_VERSION
CONCEPT_VOCAB_VERSION_tmp=condition_concept_df_tmp %>%
  group_by(concept_id) %>%
  distinct(vocabulary_version,.keep_all = TRUE) %>%
  # mutate(test=n_distinct(vocabulary_version)) %>%
  summarize(CONCEPT_VOCAB_VERSION = str_c((tolower(vocabulary_version)), collapse = "| ")) 

    # check
    # head(CONCEPT_VOCAB_VERSION_tmp)
    # table(CONCEPT_VOCAB_VERSION_tmp$test)
    # dim(CONCEPT_VOCAB_VERSION_tmp)
    # dim(condition_concept_df_tmp)

# merge new variables into dataframe
#----------------------------------

# CONCEPT_SOURCE_CODE
condition_concept_df_tmp1=left_join(condition_concept_df_tmp, CONCEPT_SOURCE_CODE_tmp)

# CONCEPT_SOURCE_LABEL
condition_concept_df_tmp2=left_join(condition_concept_df_tmp1, CONCEPT_SOURCE_LABEL_tmp)

# CONCEPT_VOCAB
condition_concept_df_tmp3=left_join(condition_concept_df_tmp2, CONCEPT_VOCAB_tmp)

# CONCEPT_VOCAB_VERSION
condition_concept_df_tmp4=left_join(condition_concept_df_tmp3, CONCEPT_VOCAB_VERSION_tmp)

# rename and select variables of interest 
condition_concept_df = condition_concept_df_tmp4 %>%
  rename(STANDARD_CONCEPT=standard_concept,
         CONCEPT_ID=concept_id,
         CONCEPT_LABEL=concept_name) %>%
  select(CONCEPT_ID,CONCEPT_SOURCE_CODE,CONCEPT_LABEL,CONCEPT_SOURCE_LABEL,CONCEPT_VOCAB,CONCEPT_VOCAB_VERSION)

head(condition_concept_df)

# 
# list the concept-ids from Conditions Concept Dataset
ccdf_concept_id=condition_concept_df$CONCEPT_ID

```




```{r}

# Create Condition Ancestors Dataset (condition_ancestor_df)

# Merge the Concept table with the ancestor table:  Primary key: concept_id 
                             
concept_ancestor_merged=full_join(concept,concept_ancestor,by='concept_id')

# Merge the above table with the vocabulary table:  Primary key: vocabulary_id 
                             
concept_ancestor_df_tmp=full_join(concept_ancestor_merged,vocabulary,by='vocabulary_id') %>%
  as_tibble() %>%
  filter(descendant_concept_id %in% ccdf_concept_id,
         concept_name != "No matching concept",
         domain_id == "Condition",
         !is.na(concept_id),
         !is.null(concept_id)) 

# create ANCESTOR_CONCEPT
ANCESTOR_CONCEPT_ID_tmp=concept_ancestor_df_tmp%>%
  group_by(descendant_concept_id) %>%
  summarize(ANCESTOR_CONCEPT_ID = str_c(concept_id, collapse = "| ")) 

# create ANCESTOR_SOURCE_CODE
ANCESTOR_SOURCE_CODE_tmp = concept_ancestor_df_tmp %>%
  group_by(descendant_concept_id) %>%
  mutate(ANCESTOR_SOURCE_CODE_tmp = paste0(tolower(vocabulary_id),":",tolower(concept_code))) %>%
  summarize(ANCESTOR_SOURCE_CODE = str_c(ANCESTOR_SOURCE_CODE_tmp, collapse = "| "))

# create ANCESTOR_VOCAB
ANCESTOR_VOCAB_tmp = concept_ancestor_df_tmp %>%
  group_by(descendant_concept_id) %>%
  distinct(vocabulary_id,.keep_all = TRUE) %>%
  mutate(count=n_distinct(vocabulary_id)) %>%
  # filter(count==2) %>%
  summarize(ANCESTOR_VOCAB = str_c(vocabulary_id, collapse = "| ")) 

# create ANCESTOR_VOCAB_VERSION
ANCESTOR_VOCAB_VERSION_tmp = concept_ancestor_df_tmp %>%
  group_by(descendant_concept_id) %>%
  distinct(vocabulary_version,.keep_all = TRUE) %>%
  mutate(count=n_distinct(vocabulary_version)) %>%
  # filter(count==2) %>%
  summarize(ANCESTOR_VOCAB_VERSION = str_c(vocabulary_version, collapse = "| ")) 

# merge new variables into dataframe
#----------------------------------

# ANCESTOR_CONCEPT_ID
concept_ancestor_df_tmp1=left_join(concept_ancestor_df_tmp, ANCESTOR_CONCEPT_ID_tmp)

# ANCESTOR_SOURCE_CODE
concept_ancestor_df_tmp2=left_join(concept_ancestor_df_tmp1, ANCESTOR_SOURCE_CODE_tmp)

# ANCESTOR_VOCAB
concept_ancestor_df_tmp3=left_join(concept_ancestor_df_tmp2, ANCESTOR_VOCAB_tmp)

# ANCESTOR_VOCAB_VERSION
concept_ancestor_df_tmp4=left_join(concept_ancestor_df_tmp3, ANCESTOR_VOCAB_VERSION_tmp)

# select variables of interest

concept_ancestor_df=concept_ancestor_df_tmp4 %>%
  select(descendant_concept_id,ANCESTOR_CONCEPT_ID,ANCESTOR_SOURCE_CODE,ANCESTOR_VOCAB,ANCESTOR_VOCAB_VERSION) %>%
  rename(CONCEPT_ID=descendant_concept_id)

names(concept_ancestor_df)
head(concept_ancestor_df)

# test_df=concept_ancestor_df

# output from UFRC
save(concept_ancestor_df, file = "concept_ancestor_df.RData")
  
# load(file="V:/FACULTY/DJLEMAS/BENCHMARK_DATA/OMOP2OBO/cancer/data_release/concept_ancestor_test.RData")

```
